---
- name: Configuro servidor base de datos ubuntu
  hosts: database
  vars:
    ansible_python_interpreter: /usr/bin/python3
    mysql_root_password: ""  # Deja vacío si no hay contraseña
  become: true
  user: sysadmin

  tasks:
    - name: UFW instalado
      ansible.builtin.apt:
        name: ufw
        state: present

    - name: Habilitar UFW
      ansible.builtin.command:
        cmd: ufw --force enable
      become: true

    - name: Servicio UFW levantado y activo
      ansible.builtin.systemd:
        name: ufw
        state: started
        enabled: true

    - name: Permitir el puerto 22 en ufw
      community.general.ufw:
        rule: allow
        name: OpenSSH

    - name: Permitir tráfico saliente
      community.general.ufw:
        state: enabled
        rule: allow
        direction: out

    - name: Denegar tráfico entrante por defecto
      community.general.ufw:
        state: enabled
        rule: deny
        direction: in

    - name: Permitir tráfico entrante en el puerto 3306 para MariaDB
      community.general.ufw:
        rule: allow
        port: '3306'
        protocol: tcp
        direction: in

    - name: Verificar estado del servicio UFW
      ansible.builtin.systemd:
        name: ufw
        state: started
        enabled: true

    ## Instalación de la base de datos
    - name: MariaDB instalado
      ansible.builtin.apt:
        name: mariadb-server
        state: present

    - name: Servidor MariaDB reiniciado
      ansible.builtin.systemd:
        name: mariadb
        state: restarted
        enabled: true

    - name: Permitir conexiones remotas para root
      community.mysql.mysql_user:
        name: root
        host: "%"
        priv: "*.*:ALL,GRANT"
        state: present
      become: true

    - name: Verificar estado del servicio MariaDB
      ansible.builtin.systemd:
        name: mariadb
        state: started

    ## Probar conexión a MySQL sin contraseña
    - name: Probar conexión a MySQL
      command: mysql -h 192.168.56.104 -u root -e "SHOW DATABASES;"
      register: mysql_test
      ignore_errors: yes

    - debug:
        msg: "Conexión a MySQL exitosa: {{ mysql_test.stdout }}"

    ## Configuración de la base de datos
    - name: Creo la base de datos "todo"
      community.mysql.mysql_db:
        check_implicit_admin: yes
        login_host: "192.168.56.104"
        login_user: root
        name: todo
        state: import
        target: "./files/todo.sql"
      delegate_to: localhost
      connection: local
