[centos]
server1    ansible_host=192.168.56.102

[ubuntu]
server2    ansible_host=192.168.56.104 
server3    ansible_host=192.168.56.20

[database]
server3    ansible_host=192.168.56.20

[linux:children]
centos
ubuntu
